[package]
name = "pconst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
vfscore = { git = "https://github.com/os-module/rvfs.git" }
pod = { workspace = true }
int-enum = "1"

[features]
default = ["riscv"]
riscv = []

