[package]
name = "virtio_mmio_input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = { path = "../../../base/constants" }
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
ksync = { path = "../../../base/ksync" }
basic = { path = "../../../domain-tools/basic" }
virtio-drivers = { git = "https://github.com/os-module/safe-virtio-drivers.git" }
virtio_mmio_common = { path = "../virtio_mmio_common" }
spin = { workspace = true }