# 编译的目标平台
[build]
target = "riscv64gc-unknown-none-elf"

# 使用我们的 linker script 来进行链接
[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tuser/apps/linker.ld",
]


[profile.release]
panic = "abort"
lto = true
strip = true
opt-level = "z"  # Optimize for size.