[package]
name = "ksync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../../base/config" }
arch = { path = "../../../base/arch" }
kernel-sync = { git = "https://github.com/os-module/kernel-sync.git" }
