[package]
name = "buf_input"
version = "0.1.0"
edition = "2021"


[dependencies]
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
basic = { path = "../../../domain-tools/basic" }

spin = "0"