[package]
name = "gblk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsyscall = {path = "../../../domain-tools/libsyscall"}
rref = {path = "../../../domain-tools/rref"}
blk = {path = "../../drivers/blk"}
interface = {path = "../../../domain-tools/interface"}