[package]
name = "gvfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsyscall = { path = "../../../domain-tools/libsyscall", features = ["domain"] }
rref = { path = "../../../domain-tools/rref" }
interface = { path = "../../../domain-tools/interface", default-features = false, features = ["vfs","domain"] }

vfs = { path = "../../vfs" }