[package]
name = "shadow_blk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
basic = { path = "../../../domain-tools/basic" }
ksync = { path = "../../../domain-tools/safety-abstraction/ksync" }

constants = { path = "../../../base/constants" }
log = "0"
spin = "0"