[package]
name = "arch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = { version = "0.11", optional = true }
config = { path = "../config" }


[features]
default = ["rv"]
rv = ["riscv"]