[package]
name = "random_scheduler"
version = "0.1.0"
edition = "2021"


[dependencies]
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
basic = { path = "../../../domain-tools/basic" }
task_meta = { path = "../../../domain-tools/task_meta" }
common_scheduler = { path = "../common_scheduler" }