[package]
name = "uart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface", default-features = false, features = ["uart","devices"] }
rref = { path = "../../../domain-tools/rref" }
basic = { path = "../../../domain-tools/basic" }
region = { path = "../../../domain-tools/safety-abstraction/region" }
constants = { path = "../../../base/constants" }

spin = "0"