[package]
name = "region"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#mem = { path = "../../../tcb/mem" }
constants = { path = "../../../tcb/constants" }
libsyscall = { path = "../../libsyscall", features = ["domain"] }