[package]
name = "gsyscall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malloc = { path = "../../../domain-tools/malloc" }
libsyscall = { path = "../../../domain-tools/libsyscall", features = ["domain"] }
rref = { path = "../../../domain-tools/rref" }
interface = { path = "../../../domain-tools/interface", default-features = false, features = ["vfs","syscall","task","domain"] }

syscall = { path = "../../syscall" }