[package]
name = "procfs"
version = "0.1.0"
edition = "2021"


[dependencies]
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
basic = { path = "../../../domain-tools/basic" }

generic = { path = "../generic" }
vfscore = { git = "https://github.com/os-module/rvfs.git", features = ["linux_error"] }
dynfs = { git = "https://github.com/os-module/rvfs.git" }
log = "0"