[package]
name = "goldfish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malloc = { path = "../../../domain-tools/malloc" }
interface = { path = "../../../domain-tools/interface", default-features = false, features = ["rtc"] }
rref = { path = "../../../domain-tools/rref" }
libsyscall = { path = "../../../domain-tools/libsyscall",features = ["domain"] }


region = { path = "../../../domain-tools/safety-abstraction/region" }

# it should be replaced by our implementation
time = { version = "0.3.7" ,default-features = false,features = ["macros"] }