[package]
name = "goldfish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
basic = { path = "../../../domain-tools/basic" }

rtc  = { git = "https://github.com/os-module/rtc", branch = "dev" }
timestamp = { git = "https://github.com/Byte-OS/timestamp" }
spin = "0"