[package]
name = "goldfish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malloc = { path = "../../../domain-tools/malloc" }
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
basic = { path = "../../../domain-tools/basic" }
constants = { path = "../../../base/constants" }
spin = { workspace = true }
goldfish_rtc = { path = "../../../safe-crates/goldfish_rtc" }