[package]
name = "ramfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface" }
ramfs = { git = "https://github.com/os-module/rvfs.git" }
vfscore = { git = "https://github.com/os-module/rvfs.git" }
basic = { path = "../../../domain-tools/basic" }
ksync = { path = "../../../base/ksync" }
generic = { path = "../generic" }
log = "0"
spin = { workspace = true }