[package]
name = "ramfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
libsyscall = { path = "../../../domain-tools/libsyscall" ,features = ["domain"] }



ramfs = { git = "https://github.com/os-module/rvfs.git" }
vfscore = { git = "https://github.com/os-module/rvfs.git" }
spin  = "0"
ksync = { path = "../../../subsystems/ksync" }
log = "0"