[package]
name = "virtio-blk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsyscall = { path = "../../libsyscall", features = ["domain"] }
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers",rev = "de1c3b1"}
#virtio-drivers = { path = "../../../../virtio-drivers" }