[package]
name = "domain-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mem = {path = "../mem"}
config = {path = "../config"}
xmas-elf = "0.9"
log = "0"
domain-helper = {path = "../domain-helper"}
platform = {path = "../platform"}
proxy = { path = "../proxy" }


libsyscall = {path = "../../domain-tools/libsyscall"}
interface = {path = "../../domain-tools/interface"}
rref = {path = "../../domain-tools/rref"}

