[build]
target = "riscv64gc-unknown-linux-musl"
#target = "x86_64-unknown-linux-musl"
[profile.release]
lto = true
strip = true
opt-level = 3  # Optimize for size.
#incremental = true
#debug = true
panic = "abort"

[target.riscv64gc-unknown-linux-musl]
rustflags = [
    "-L/opt/riscv-musl/lib/gcc/riscv64-linux-musl/11.2.1/",
    "-L/opt/riscv-musl/riscv64-linux-musl/lib",
#    "-C", "link-args=-lc",
#    "-C", "prefer-dynamic",
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-lgcc"
]
linker = "riscv64-linux-musl-gcc"