[package]
name = "interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rref = { path = "../rref" }
constants = { path = "../../tcb/constants" }

[features]
default = ["blk","fs","uart","gpu","input","vfs", "rtc", "cache_blk","plic", "devices", "task"]
domain = []
blk = []
cache_blk = []
fs = []
uart = []
gpu = []
input = []
vfs = []
rtc = []
plic = []
devices = []
task = []