[package]
name = "interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rref = { path = "../rref" }
constants = { path = "../../base/constants" }

[features]
default = [
    "blk",
    "fs",
    "uart",
    "gpu",
    "input",
    "vfs",
    "rtc",
    "cache_blk",
    "plic",
    "devices",
    "task",
    "syscall",
    "shadow_blk",
    "buf_uart"
]
domain = []
blk = []
cache_blk = []
shadow_blk = []
fs = []
uart = []
gpu = []
input = []
vfs = []
rtc = []
plic = []
devices = []
task = []
syscall = []
buf_uart = []