[alias]
server = "run -p domain-server --"


[profile.release]
strip = true
#incremental = true
#debug = true
opt-level = 3
lto = true

[target.riscv64]
#rustflags = [
#    "-Cforce-unwind-tables=yes",
#    "-Clink-args=--eh-frame-hdr",
#    "-Cforce-frame-pointers=yes"
#]