[package]
name = "blk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malloc = {path = "../../../domain-tools/malloc"}
interface = {path = "../../../domain-tools/interface" }
rref = {path = "../../../domain-tools/rref"}
virtio-blk = { path = "../../../subsystems/safety-abstraction/virtio-blk" }
libsyscall = { path = "../../../domain-tools/libsyscall" }



log = "0"