[package]
name = "blk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers"}
basic = { path = "../../../domain-tools/basic" }
ksync = { path = "../../../domain-tools/safety-abstraction/ksync" }
region = { path = "../../../domain-tools/safety-abstraction/region" }
constants = { path = "../../../base/constants" }



spin = "0"
log = "0"