[package]
name = "ptable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../tcb/config" }

page_table = { git = "https://github.com/rcore-os/arceos", rev = "92609cc"}
memory_addr = { git = "https://github.com/rcore-os/arceos", rev = "92609cc"}

