[package]
name = "ptable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../base/config" }
page_table = { path = "../page_table" }
memory_addr = {  path = "../memory_addr" }
pod = { workspace = true }