[package]
name = "gcache_blk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malloc = { path = "../../../domain-tools/malloc" }
corelib = { path = "../../../domain-tools/corelib" }
basic = { path = "../../../domain-tools/basic" }
rref = { path = "../../../domain-tools/rref" }
interface = { path = "../../../domain-tools/interface", default-features = false, features = ["cache_blk","domain"] }

cache_blk = { path = "../../drivers/cache_blk" }