[package]
name = "devfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface" }
basic = { path = "../../../domain-tools/basic" }
rref = { path = "../../../domain-tools/rref" }

devfs = { git = "https://github.com/os-module/rvfs.git" }
vfscore = { git = "https://github.com/os-module/rvfs.git", features = ["linux_error"] }
generic = { path = "../generic" }
pod = { git = "https://github.com/asterinas/pod", rev = "d7dba56" }
log = "0"
spin = "0"