[package]
name = "input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = { path = "../../../base/constants" }
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers",rev = "de1c3b1"}
ksync = { path = "../../../base/ksync" }
basic = { path = "../../../domain-tools/basic" }

spin = { workspace = true }