[package]
name = "fifo_scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basic = { path = "../../../domain-tools/basic", features = ["task"] }
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
task_meta = { path = "../../../domain-tools/task_meta" }
common_scheduler = { path = "../common_scheduler" }

log = "0"