[package]
name = "cache_blk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malloc = { path = "../../../domain-tools/malloc" }
interface = { path = "../../../domain-tools/interface", default-features = false, features = ["cache_blk","blk","domain"] }
rref = { path = "../../../domain-tools/rref" }
libsyscall = { path = "../../../domain-tools/libsyscall", features = ["domain"] }
ksync = { path = "../../../tcb/ksync" }


log = "0"
lru = "0"