[package]
name = "domain-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../config" }
mem = { path = "../mem" }
ksync = { path = "../ksync" }
platform = { path = "../platform" }
arch = { path = "../arch" }

libsyscall = { path = "../../domain-tools/libsyscall" }
rref = { path = "../../domain-tools/rref" }
continuation = { path = "../../domain-tools/continuation" }
proxy = { path = "../proxy" }


log = "0"
spin = "0"
