[package]
name = "domain-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../config" }
mem = { path = "../mem" }
ksync = { path = "../ksync" }
spin = "0"
platform = { path = "../platform" }
arch = {path = "../arch"}
log = "0"

libsyscall = { path = "../../domain-tools/libsyscall" }
rref = { path = "../../domain-tools/rref" }
continuation = { path = "../../domain-tools/continuation" }
proxy = { path = "../proxy" }