[package]
name = "domain-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = {path = "../config"}
libsyscall = {path = "../../domain-tools/libsyscall"}
mem = {path = "../mem"}
ksync = {path = "../ksync"}
spin = "0"
platform = {path = "../platform"}
arch = {path = "../arch"}
