[package]
name = "uart16550"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
basic = { path = "../../../domain-tools/basic" }
constants = { path = "../../../base/constants" }
raw_uart16550 = { path = "../../../safe-crates/raw_uart16550" }
spin = { workspace = true }