[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
fs_extra = "1.3.0"
toml = "0.8.12"
serde = { version = "1",features = ["derive"] }