[package]
name = "kuart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface", default-features = false, features = ["uart","domain"] }
rref = { path = "../../../domain-tools/rref" }
basic = { path = "../../../domain-tools/basic" }
ksync = { path = "../../../domain-tools/safety-abstraction/ksync" }
constants = { path = "../../../base/constants" }