[package]
name = "gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface", default-features = false, features = ["gpu"] }
rref = { path = "../../../domain-tools/rref" }
libsyscall = { path = "../../../domain-tools/libsyscall" }