[package]
name = "constants"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pconst = { git = "https://github.com/os-module/pconst.git", features = ["trick"] }
