[package]
name = "generic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../../domain-tools/interface" }
rref = { path = "../../../domain-tools/rref" }
basic = { path = "../../../domain-tools/basic" }
constants = { path = "../../../base/constants" }
vfscore = { git = "https://github.com/os-module/rvfs.git" }
ksync = { path = "../../../base/ksync" }
log = "0"
spin = { workspace = true }