[package]
name = "page_table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memory_addr = {  path = "../memory_addr" }
bitflags = { workspace = true }
log = { workspace = true }