on: [push, pull_request]

name: Tests

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
          os: ["macos-latest", "ubuntu-latest", "windows-latest"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo test
        run: cargo test --all-targets --all-features
